#PBS -q ai
#PBS -l walltime=168:00:00
#PBS -l select=1:ncpus=6:ngpus=1:mem=100gb
#PBS -N struc_aln_0.1
#PBS -o ./log
#PBS -e ./log

source $CONDA_PREFIX/../bin/activate $CONDA_PREFIX
cd .


export HF_ENDPOINT=https://hf-mirror.com
alpha=0.1
CUDA_VISIBLE_DEVICES=0 python compute_fitness.py \
    --model_name AI4Protein/ProSST-2048 \
    --logit_mode struc_seq_aln \
    --alpha $alpha \
    --model_out_name ProSST-2048-struc_aln"$alpha" \
    --base_dir data/proteingym_v1 \
    --out_scores_dir result/proteingym_v1