#!/bin/bash
# Simple evcouplings MSA runner: 12 parallel proteins, 9 bitscores each (high→low).
# Configs must already exist (generated by Phase 1).
# Usage: nohup bash script/msa/run_mavedb_simple.sh > log/run_mavedb2.log 2>&1 &

CONDA_BIN=$CONDA_PREFIX/bin
WORKDIR=.
UNIQUE_LIST=$WORKDIR/data/mavedb/unique_proteins.txt
BITSCORES="0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1"

CORES_PER_JOB=8
PARALLEL=12

export PATH=$CONDA_BIN:$PATH
cd $WORKDIR
mkdir -p log

run_one() {
    local protein=$1
    local job_id=$2
    local outdir="output/mavedb/$protein"
    local logfile="log/evcouplings_${protein}.log"

    if [ -f "$outdir/${protein}_job_statistics_summary.csv" ]; then
        echo "[SKIP] $protein"
        return 0
    fi

    local core_start=$(( (job_id % PARALLEL) * CORES_PER_JOB ))
    local core_end=$(( core_start + CORES_PER_JOB - 1 ))

    echo "[START] $protein cores=${core_start}-${core_end} $(date)"
    echo "[START] $(date)" > "$logfile"

    local all_configs=""
    local ok=0
    local fail=0

    for b in $BITSCORES; do
        local bcfg="${outdir}/${protein}_b${b}_config.txt"
        [ ! -f "$bcfg" ] && continue
        all_configs="$all_configs $bcfg"

        echo "[RUN] b${b} $(date)" >> "$logfile"
        taskset -c ${core_start}-${core_end} evcouplings_runcfg "$bcfg" >> "$logfile" 2>&1
        if [ $? -eq 0 ]; then
            ok=$((ok+1))
        else
            fail=$((fail+1))
            echo "[FAIL] b${b}" >> "$logfile"
        fi
    done

    local global_cfg="${outdir}/${protein}_config.txt"
    if [ -f "$global_cfg" ] && [ -n "$all_configs" ]; then
        taskset -c ${core_start}-${core_end} evcouplings_summarize protein_monomer "$outdir/$protein" $all_configs >> "$logfile" 2>&1
    fi

    # Generate summary CSV from outcfg files (evcouplings_summarize doesn't produce it without compare stage)
    $CONDA_BIN/python3 $WORKDIR/script/msa/generate_summary.py "$outdir" >> "$logfile" 2>&1

    if [ $fail -eq 0 ]; then
        echo "[DONE] $protein ok=$ok $(date)"
    else
        echo "[PARTIAL] $protein ok=$ok fail=$fail $(date)"
    fi
}

export -f run_one
export CONDA_BIN WORKDIR BITSCORES PARALLEL CORES_PER_JOB

echo "========================================"
echo "  evcouplings MSA (simple runner)"
echo "  Parallel: $PARALLEL x ${CORES_PER_JOB} cores"
echo "  Proteins: $(wc -l < $UNIQUE_LIST)"
echo "  Time:     $(date)"
echo "========================================"

# Run with xargs, passing line number as job_id for core assignment
nl -ba $UNIQUE_LIST | xargs -P $PARALLEL -L 1 bash -c 'run_one "$2" "$1"' _

echo "=== All done $(date) ==="
